language: ruby
rvm:
  - 1.8.7
script:
  - "rake lint"
  - "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.6.2
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=3.1.0
gemfile: .gemfile
