name 'jlyheden-zabbix'
version '0.0.1'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://github.com/jlyheden/puppet-zabbix'
source 'git://github.com/jlyheden/puppet-zabbix.git'
summary 'Module for managing Zabbix'
description 'Puppet module for managing the Zabbix agent, server, frontend and proxy'
